# Generated by Django 3.1.2 on 2020-10-09 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=250)),
                ('data', models.CharField(max_length=85000)),
                ('date', models.DateTimeField(default=1602252909.305956)),
            ],
        ),
    ]
