# Generated by Django 3.1.2 on 2020-10-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smp_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cache',
            name='date',
            field=models.FloatField(),
        ),
    ]
