# Generated by Django 3.1.2 on 2020-10-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smp_api', '0002_auto_20201009_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Twitter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Set name for this pair API keys', max_length=250)),
                ('access_api', models.CharField(max_length=500)),
                ('access_secret', models.CharField(max_length=500)),
                ('consumer_key', models.CharField(max_length=500)),
                ('consumer_secret', models.CharField(max_length=500)),
            ],
        ),
    ]
