# Generated by Django 3.1.2 on 2020-10-09 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smp_api', '0003_twitter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twitter',
            old_name='access_api',
            new_name='access_token_key',
        ),
        migrations.RenameField(
            model_name='twitter',
            old_name='access_secret',
            new_name='access_token_secret',
        ),
    ]
