# Generated by Django 3.1.2 on 2020-10-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smp_api', '0004_auto_20201009_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=400)),
                ('port', models.CharField(max_length=60)),
                ('login', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('is_fb', models.BooleanField(default=True)),
                ('is_browser', models.BooleanField(default=True)),
            ],
        ),
    ]
