# Generated by Django 3.1.2 on 2020-10-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smp_api', '0005_proxy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='login',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='password',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
