# Generated by Django 3.1.2 on 2020-10-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smp_api', '0006_auto_20201013_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urls', models.TextField(max_length=25000)),
            ],
        ),
    ]
