# Generated by Django 3.1.2 on 2020-10-28 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smp_api', '0007_testurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=580)),
                ('result', models.CharField(max_length=10000)),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 10, 28, 19, 33, 11, 265410))),
            ],
        ),
    ]
