# Generated by Django 3.1.2 on 2020-10-28 19:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('smp_api', '0008_queue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 28, 19, 33, 52, 573147, tzinfo=utc)),
        ),
    ]
