# Generated by Django 3.1.2 on 2020-10-28 19:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('smp_api', '0009_auto_20201028_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='queue',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 28, 19, 36, 30, 749532, tzinfo=utc)),
        ),
    ]
