# Generated by Django 3.1.2 on 2020-10-28 19:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('smp_api', '0010_auto_20201028_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 28, 19, 37, 38, 223273, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='queue',
            name='result',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
